import type { WorkflowDag } from "../types";
import type { ArenaChallenge } from "../data/arenaChallenges";
import { exportBundle as exportVeniceBundle } from "./veniceExporter";
import { exportBundle as exportChallengeFiles } from "./starterExporter";

/** Keep the Venice runner verbatim while packaging the editable challenge files. */
export function exportBundle(dag: WorkflowDag, challenge: ArenaChallenge | null = null): Record<string, string> {
  const challengeFiles = exportChallengeFiles(dag, challenge);
  const original = exportVeniceBundle(dag);
  return {
    "mission.json": challengeFiles["mission.json"],
    "workflow.json": challengeFiles["workflow.json"],
    "src/types.ts": challengeFiles["src/types.ts"],
    "src/adapters.ts": challengeFiles["src/adapters.ts"],
    "src/pipeline.ts": challengeFiles["src/pipeline.ts"],
    ...original,
    "README.md": "# NexusRelay Venice runner\n\nThis runner.ts is generated by the original Venice exporter without edits. Run `npm install`, set TAVILY_API_KEY, TAVILY_API_URL, JEV_GATEWAY_URL, JEV_API_KEY, and WEBHOOK_BEARER in the process environment, then `npm start`. The generated DAG still contains the original example REST destinations; change those in the Studio before dispatching. The original runner has a local Jev fallback, an empty Tavily result when keys are absent, and a DRY_RUN option. Those behaviors are part of the source as written. `mission.json` and `workflow.json` preserve your challenge and full node prompts; `runner.ts` embeds the original slim DAG.\n",
  };
}
